version: '3.7'
services:
  resume:
    build: .
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resume.entrypoints=http"
      - "traefik.http.routers.resume.rule=Host(`ekwav.coflnet.com`,`lukas.simmet.top`)"
      - "traefik.http.routers.traefik.middlewares=https-redirect@file"
      - "traefik.http.routers.resume-secure.entrypoints=https"
      - "traefik.http.routers.resume-secure.rule=Host(`ekwav.coflnet.com`,`lukas.simmet.top`)"
      - "traefik.http.routers.resume-secure.tls=true"
      - "traefik.http.routers.resume-secure.tls.certresolver=http"
      - "traefik.http.routers.resume-secure.service=resume"
      - "traefik.http.services.resume.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true